services:
  db:
    image: postgis/postgis:15-3.3
    container_name: pickmylunch-postgis
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: pickmylunch-redis
    ports:
      - "6379:6379"
    restart: always

  api-server:
    build: ./api-server
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT=${JWT}
    depends_on:
      - db
      - redis

  batch-server:
    build: ./batch-server
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_KEY=${API_KEY}
      - API_BASE_URL=${API_BASE_URL}
      - API_SERVICE_NAME=${API_SERVICE_NAME}
      - API_FORMAT_TYPE=${API_FORMAT_TYPE}
      - API_PAGE_SIZE=${API_PAGE_SIZE}
      - API_MAX_INDEX=${API_MAX_INDEX}
    depends_on:
      - db

volumes:
  pgdata: