server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379

jwt:
  prefix: 'Bearer '
  secret-key: ${JWT}
  access-token-validity-in-minutes: 25
  refresh-token-validity-in-minutes: 4320
  access-header: Authentication
  refresh-header: refresh-token

cookie:
  limit-time: 259200
  accepted-url: '/api/auth/reissue'
  cookie-name: refresh-token
  domain: localhost

app:
  member:
    anonymized-name: 탈퇴회원
    anonymized-email: deleted@example.com

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
